# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g node-gyp
    npm install
    npm run build:all
  displayName: 'npm install and build'
  env:
    GH_TOKEN: $(gh.token)

- task: CopyFiles@2
  inputs:
    Contents: |
     '$(Build.SourcesDirectory)/dist/**'
     '$(Build.SourcesDirectory)/hook.js'
     '$(Build.SourcesDirectory)/hook-installer.js'
     '$(Build.SourcesDirectory)/package.json'
     '$(Build.SourcesDirectory)/README.md'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/package'
  displayName: 'Copy files to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/package'
    ArtifactName: 'package'
    
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.SourcesDirectory)/dist'
#    ArtifactName: 'electron-apps'
#    PublishLocation: 'Container'