# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g node-gyp
    npm install
    npm run build:all
  displayName: 'npm install and build'
  env:
    GH_TOKEN: $(gh.token)

- script: |
    npm pack
  displayName: 'npm package'

- task: CopyFiles@2
  inputs:
    Contents: '*.tgz'
    TargetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy packages to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory) 
    ArtifactName: 'package'
    
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.SourcesDirectory)/dist'
#    ArtifactName: 'electron-apps'
#    PublishLocation: 'Container'